class StringConstant {
  static const EN = {
    "loading"              : "loading",
    "data_empty"           : "no data",
    "data_comment_empty"   : "no comment data",
    "data_recommend_empty" : "no recommend data",
    "see_all"              : "SeeAll",
    "server"               : "Server",
    "choice"               : "Choice",
    "search"               : "search goods",
    "search_btn"           : "Search",
    "search_history"       : "SearchHistory",
    "buy_btn"              : "Buy",
    "title"                : "XinLeJi•OfficialMall",
    "bottom_navigate_home" : "Home",
    "bottom_navigate_cate" : "Cate",
    "bottom_navigate_cart" : "Cart",
    "bottom_navigate_user" : "User",
    "scan"                 : "Scan",
    "code"                 : "Code",
    "male"                 : "Male",
    "female"               : "Female",
    "tab_goods"            : "Goods",
    "tab_detail"           : "Detail",
    "tab_comment"          : "Comment",
    "tab_recommend"        : "Recommend",
    "goods_detail_title"   : "GoodsDetail",
    "goods_detail_tip"     : "─────• GoodsDetail •─────",
    "goods_like_tip"       : "YouLike",
    "goods_comment_tip"    : "Comment",
    "goods_list_title"     : "GoodsList",
    "goods_sort_default"   : "default",
    "goods_price_sort_asc" : "price asc",
    "goods_price_sort_desc": "price desc",
    "goods_newest"         : "newest",
    "goods_likely"         : "likely",
    "goods_filter"         : "filter",
    "goods_asc"            : "asc",
    "goods_desc"           : "desc",
    "chosed_tip"           : "has chosed",
    "chosed_size"          : "size",
  };

  static const ZN = {
    "loading"              : "加载中",
    "data_empty"           : "暂无数据",
    "data_comment_empty"   : "暂无评论",
    "data_recommend_empty" : "暂无推荐",
    "see_all"              : "查看全部",
    "server"               : "服务",
    "choice"               : "已选",
    "search"               : "潮流单品搜一下",
    "search_btn"           : "搜索",
    "search_history"       : "搜索历史",
    "buy_btn"              : "购买",
    "title"                : "新乐纪•官方商城",
    "bottom_navigate_home" : "首页",
    "bottom_navigate_cate" : "分类",
    "bottom_navigate_cart" : "购物车",
    "bottom_navigate_user" : "会员中心",
    "scan"                 : "扫一扫",
    "code"                 : "会员吗",
    "male"                 : "男子",
    "female"               : "女子",
    "tab_goods"            : "宝贝",
    "tab_detail"           : "详情",
    "tab_comment"          : "评价",
    "tab_recommend"        : "推荐",
    "goods_detail_title"   : "宝贝详情",
    "goods_detail_tip"     : "─────• 宝贝详情 •─────",
    "goods_like_tip"       : "猜你喜欢",
    "goods_comment_tip"    : "宝贝评价",
    "goods_list_title"     : "商品列表",
    "goods_sort_default"   : "默认",
    "goods_price_sort_asc" : "价格升序",
    "goods_price_sort_desc": "价格降序",
    "goods_newest"         : "新品",
    "goods_likely"         : "人气",
    "goods_filter"         : "筛选",
    "goods_asc"            : "升序",
    "goods_desc"           : "降序",
    "chosed_tip"           : "已选择",
    "chosed_size"          : "码",
  };
  
  static const String shopServiceStr = "商家发货&售后；7天无理由退换；货到付款；...";
  static const List<String> shopServiceList = ["正品保障", "7天无理由退换", "全场满300免邮", "支持线下店铺自提"];
  static const List<String> shopServiceSubList = ["专业精选，正品护航", 
    "消费者在满足7天无理由退换货申请条件的前提下，可以提出\"7天无理由退换货\"的申请", 
    "全场订单满300元即可免邮费", "同城有线下店铺的，可支持到店提货"];
}